version: '3'

services:
  server:
    build:
      context: ./
    ports:
      - "4000:4000"

  frontend:
    build:
      context: ./frontend
    ports:
      - 3000:80
    depends_on:
      - server